version: '2'
services:
  mysql:
    build: ./docker/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
    volumes:
      - db:/var/lib/mysql
  web:
    build: ./docker/web
    command: ./docker/web/entrypoint.sh
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
volumes:
  db:
